// SPDX-License-Identifier: ISC
//
// Copyright (c) 2008, Mukunda Johnson (mukunda@maxmod.org)

.ifndef MP_FORMAT_MAS_INC
.equ	MP_FORMAT_MAS_INC, 1

// Sample structure : mm_mas_gba_sample

.equ	C_SAMPLE_LEN	,0
.equ	C_SAMPLE_LOOP	,4
.equ	C_SAMPLE_DATA	,12

// Sample structure : mm_mas_ds_sample

.equ	C_SAMPLEN_LSTART,0
.equ	C_SAMPLEN_LEN	,4
.equ	C_SAMPLEN_FORMAT,8
.equ	C_SAMPLEN_REP	,9
.equ	C_SAMPLEN_DFREQ	,10
.equ	C_SAMPLEN_POINT	,12
.equ	C_SAMPLEN_DATA	,16

.endif
